feat: Realtime HTTP APIs
tigrisdata/tigris-api pull request #172
Opened 2022-12-15 04:55 UTC by himank

2022-12-15 07:01 UTC, adilansari commented on server/v1/realtime.proto
> +message ListSubscriptionResponse {
this might need some sort of pagination for HTTP

2022-12-15 07:02 UTC, adilansari submitted a review, later dismissed

2022-12-15 13:35 UTC, garrensmith requested changes
See my note on the channel rpc call. It breaks when trying to use it in the js client

2022-12-15 13:35 UTC, garrensmith commented on server/v1/realtime.proto
> +  rpc GetChannel(GetChannelRequest) returns (GetChannelResponse) {
we will have to rename `GetChannel` and `GetChannels` methods. The underlying client in Typescript already has those two methods for internal usage so we get a typescript error and would get a runtime error as well:

```
roperty 'getChannel' in type 'RealtimeClient' is not assignable to the same property in base type 'Client'.
  Type '{ (request: GetChannelRequest, callback: (error: ServiceError, response: GetChannelResponse) => void): SurfaceCall; (request: GetChannelRequest, metadata: Metadata, callback: (error: ServiceError, response: GetChannelResponse) => void): SurfaceCall; (request: GetChannelRequest, metadata: Metadata, options: Partial<....' is not assignable to type '() => Channel'.

111     public getChannel(request: server_v1_realtime_pb.GetChannelRequest, callback: (error: grpc.ServiceError | null, response: server_v1_realtime_pb.GetChannelResponse) => void): grpc.ClientUnaryCall;
```

Maybe something like `GetTigrisChannel` or `GetMsgChannel` or `GetRTChannel`

2022-12-15 18:12 UTC, himank commented on server/v1/realtime.proto
> +message ListSubscriptionResponse {
ack, let me add limit and offset for now.

2022-12-15 19:59 UTC, himank commented on server/v1/realtime.proto
> +message ListSubscriptionResponse {
Or page similar to Search APIs.

2022-12-15 20:21 UTC, efirs approved these changes

2022-12-15 20:53 UTC, adilansari commented on server/v1/realtime.proto
> +message ListSubscriptionResponse {
We should add total subscriptions and total pages here as well. That helps bottom-up traversal, or why suddenly pagination stopped returning results etc.

2022-12-15 20:56 UTC, adilansari submitted a review, later dismissed
we can add suggestions later

2022-12-15 21:00 UTC, himank commented on server/v1/realtime.proto
> +message ListSubscriptionResponse {
sure, once the response is finalized will add it.

2022-12-16 06:43 UTC, garrensmith approved these changes
Tested in js client and it now passes compile stage.

2022-12-16 18:28 UTC, garrensmith commented on server/v1/realtime.proto
> +  string action=1;
Lets remove action and instead add in new event types for `presence`.

2022-12-16 18:28 UTC, garrensmith commented on server/v1/realtime.proto
> +  string event_type=2;
Can we make this an enum

2022-12-16 18:28 UTC, garrensmith commented on server/v1/realtime.proto
> +  string timestamp=4;
lets remove timestamp for now and we can add it back later if we need it. 
Add in a `seq` instead that shows the position of the message in the channel stream

2022-12-16 19:12 UTC, himank commented on server/v1/realtime.proto
> +  string timestamp=4;
actually `id` is the sequence, I completely missed it.  So there is no separate `seq` field needed.

2022-12-16 19:14 UTC, himank commented on server/v1/realtime.proto
> +  string event_type=2;
Yes, it is an enum now. We need to also publish these enum codes for HTTPs.

2022-12-16 19:37 UTC, garrensmith approved these changes

2022-12-16 19:41 UTC, merged